services:
# Nginx reverse proxy
  nginx-dev:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"  # Add HTTPS port
    volumes:
      - ./nginx.infra.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx-certs:/etc/nginx/certs:ro  # Mount certificates
    restart: unless-stopped
    network_mode: "host"
    # networks:
      # - app-network
  # Redis database
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    # networks:
      # - app-network

  # Observability stack
  otel-lgtm:
    image: docker.io/grafana/otel-lgtm:latest
    ports: 
      - "3002:3000"
      - "4317:4317"
      - "4318:4318"
    environment:
      - OTEL_METRIC_EXPORT_INTERVAL=500
    restart: unless-stopped
    # networks:
      # - app-network

volumes:
  redis_data:
    driver: local

# networks:
  # app-network:
    # driver: bridge
