packages:
  - packages/*
  - apps/*
  - libs/*

catalogs:
  effect:
    '@effect/language-service': ^0.21.0
    '@effect/platform': ^0.85.0
    '@effect/platform-browser': ^0.65.0
    '@effect/platform-node': ^0.86.0
    effect: ^3.16.7
  eslint:
    '@eslint/js': ^9.8.0
    eslint: 9.29.0
    eslint-config-prettier: ^10.0.0
  remix:
    '@remix-run/node': ^2.15.0
    '@remix-run/react': ^2.15.0
    '@remix-run/serve': ^2.15.0
    '@remix-run/dev': ^2.15.0
    '@remix-run/testing': ^2.15.0
  typescript:
    typescript: ~5.8.2
  vite:
    vite: ^6.0.0
    vitest: ^3.0.0
