packages:
  - 'packages/*'
  - 'apps/*'
  - 'libs/*'
catalogs:
  effect:
    '@effect/language-service': '^0.21.0'
    '@effect/platform': '^0.85.0'
    '@effect/platform-browser': '^0.65.0'
    '@effect/platform-node': '^0.86.0'
    effect: '^3.16.7'
