$schema: 'https://moonrepo.dev/schemas/tasks.json'

fileGroups:
  default:
    - '**/*'
  production:
    - '!**/*.{spec,test}.{js,jsx,ts,tsx}'
    - '!**/*.{spec,test}.{js,jsx,ts,tsx}.snap'
    - '!**/test-setup.{js,ts}'
    - '!tsconfig.spec.json'
    - '!.eslintrc.json'
    - '!eslint.config.mjs'
    - '!jest.config.{js,ts}'

tasks:
  build:
    outputs:
      - 'dist'
    deps: 
      - "~:build"
  clean:
    options:
      runInCI: false
    command:
    - rm
    - '-rf'
    - node_modules
    - dist
    toolchain: system

  typecheck:
    deps:
      - '^:build'
    command: 'tsc -p tsconfig.json'
    inputs:
      - '@group(production)'  # Use your filegroup
      - 'tsconfig.json'
      - '/tsconfig.base.json'  # Root reference
    
  test:
    deps:
      - '^:build'
    command: 'vitest'


  lint:
    command:
      - 'eslint'
      # Support other extensions
      - '--ext'
      - '.js,.jsx,.ts,.tsx'
      # Always fix and run extra checks
      - '--fix'
      - '--report-unused-disable-directives'
      # Dont fail if a project has nothing to lint
      - '--no-error-on-unmatched-pattern'
      # Do fail if we encounter a fatal error
      - '--exit-on-fatal-error'
      # Only 1 ignore file is supported, so use the root
      - '--ignore-pattern'
      - '@in(4)'
      # Run in current dir
      - '.'
    inputs:
      # Source and test files
      - 'src/**/*'
      - 'tests/**/*'
      # Other config files
      - '*.config.*'
      # Project configs, any format, any depth
      - '**/.eslintrc.*'
      # Root configs, any format
      - '/.eslintignore'
      - '/.eslintrc.*'
      # TypeScript support
      - 'types/**/*'
      - 'tsconfig.json'
      - '/tsconfig.eslint.json'
      - '/tsconfig.base.json'
